name: ci

on:
  push:
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore Opc.sln
      - name: Build
        run: dotnet build Opc.sln -c Release --no-restore
      - name: Test
        run: dotnet test Opc.sln -c Release --no-build
      - name: Build Docker image
        run: docker build -t opc-api:local -f ./OpcApi/Dockerfile .
